name: Awesome Multi-fidelity Fusion
title: Awesome Multi-fidelity Fusion
url: https://fillip1233.github.io/
description: This is a curated paper list of existing Multi-fidelity Fusion method for Electronic Design Automation (EDA) studies.
destination: ./_site
repository: Fillip1233/Fillip1233.github.io
twitter: joyg_phd
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#seo
tagline: A curated paper list of  EDA | Awesome Multi-fidelity Fusion | VLSI |  Artificial Intelligence | Machine Learning | Deep Learning | ML | AI | CUHK | CSE | CS
#paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
